import { createAuthClient } from "better-auth/client";
import { apiKeyClient, emailOTPClient } from "better-auth/client/plugins";
import { passkeyClient } from "@better-auth/passkey/client";

export const authClient = createAuthClient({
  plugins: [
    apiKeyClient(),
    passkeyClient(),
    emailOTPClient()
  ]
}); 

export const { signIn, signOut, signUp, useSession, passkey, requestPasswordReset, resetPassword } = authClient;

// Email OTP functions (using dynamic proxy access)
// @ts-ignore - these are dynamically generated by better-auth client proxy
export const forgetPasswordEmailOTP = authClient.emailOtp.forgetPasswordEmailOTP;
// @ts-ignore
export const requestPasswordResetEmailOTP = authClient.emailOtp.requestPasswordResetEmailOTP;
// @ts-ignore
export const resetPasswordEmailOTP = authClient.emailOtp.resetPasswordEmailOTP;

// For backward compatibility with existing components
export const forgetPassword = forgetPasswordEmailOTP;
